# shellcheck shell=bash
# shellcheck disable=SC1090
# shellcheck disable=SC2034
#
# SC1090: Can't follow non-constant source. Use a directive to specify location.
# SC2034: foo appears unused. Verify it or export it.

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="robbyrussell"

# Which plugins would you like to load?
plugins=()

source "$ZSH/oh-my-zsh.sh"

# User configuration
alias ga='git add'
alias gd='git diff'
alias gst='git status'
alias glog='git log --oneline --decorate --graph'
alias gwch='git whatchanged -p --abbrev-commit --pretty=medium'

for cfg in ~/.zshrc.d/*.sh
do
    echo "Loading config: $cfg"
    source "$cfg"
done
